export const CREATE_TODO = "CREATE_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const COMPLETE_TODO = "COMPLETE_TODO";
export const UNDO_COMPLETE_TODO = "UNDO_COMPLETE_TODO";

export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
